version: '3.4'

services:

  applicationtier.api.organizationstructure:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"


  applicationtier.api.staffing:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"


  presentationtier.blazorui.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

